// +Score_Game:int
// +Life_Score:int
// +state:int
// +Start:int
// +w:int
// +h:int
// +y:int
// +x:int
// +moveable:int
// +Stunt:int
// +Dog:int
// +Dog2:int
// +Dog3:int
// +Rand_jerry:int
// +w_jerry:int
// +h_jerry:int
// +x_jerry1:int
// +y_jerry1:int
// +x_jerry2:int
// +y_jerry2:int
// +x_jerry3:int
// +y_jerry3:int
